name: ServerTweaks
version: 0.1
description: Tweak your server
author: TBK
website: 

main: tbk.servertweaks.ServerTweaksPlugin

commands:
    stweaks:
        description: SorryHost1
        permission: stweaks.canuse
    oscmd:
        description: SorryHost2
        permission: stweaks.canuse